import 'server-only';
import { cookies } from 'next/headers';
import {
  toLocalDigits,
  formatNumber,
  formatMoney,
  formatDate,
  monthLabel,
  pickLocalized,
  pickPair,
  dayName,
  type DateFormat,
  type Lang,
} from './format';
import en from '@/lang/en.json';
import bn from '@/lang/bn.json';
import extraEn from '@/lang/extra.en.json';
import extraBn from '@/lang/extra.bn.json';

/**
 * Translation, numbers and dates — the runtime for the catalogues in lang/.
 *
 * The 4,352 keys in lang/en.json and lang/bn.json were converted straight from
 * Orbit's lang/{en,bn}/*.php by tools/lang-to-json.php. Both files hold the same
 * key set, so a missing translation is a build-time fact rather than a surprise
 * at runtime.
 *
 * Bangla is the default, as orbit_lang() defaults to 'bn'. That matters: a
 * visitor with no cookie must see the site in the language its students read.
 */

/**
 * `extra.*.json` holds keys this app needs and the PHP app never had — a page
 * that did not exist there, or wording that changed because the behaviour did.
 *
 * It is a separate file on purpose: `lang/{en,bn}.json` are generated by
 * tools/lang-to-json.php and are overwritten whenever the original catalogue
 * changes, so anything added to them by hand would quietly disappear.
 */
const DICTS: Record<Lang, Record<string, string>> = {
  en: { ...(en as Record<string, string>), ...(extraEn as Record<string, string>) },
  bn: { ...(bn as Record<string, string>), ...(extraBn as Record<string, string>) },
};

export const LANGUAGES: Record<Lang, string> = { bn: 'বাংলা', en: 'English' };

export const LANG_COOKIE = 'orbit_lang';

export function isLang(value: unknown): value is Lang {
  return value === 'bn' || value === 'en';
}

/**
 * The active language for this request.
 *
 * The PHP app looks at the session, then the `orbit_lang` cookie, then the
 * user's saved preference, then the `default_language` setting. Here the cookie
 * is the single source — it is written by the language switcher and by the
 * preference save, so it already carries the answer without a database read on
 * every page.
 */
export async function getLang(): Promise<Lang> {
  const value = (await cookies()).get(LANG_COOKIE)?.value;
  return isLang(value) ? value : 'bn';
}

/**
 * Looks up a key, falling back to English and then to the key itself.
 *
 * Returning the key rather than an empty string is deliberate: a missing
 * translation then shows as `admin.nav.fees` on the page, which someone will
 * report, instead of a blank space nobody notices.
 */
export function translate(lang: Lang, key: string, vars?: Record<string, string | number>): string {
  let text = DICTS[lang][key] ?? DICTS.en[key] ?? key;
  if (vars) {
    for (const [name, value] of Object.entries(vars)) {
      text = text.split(`{${name}}`).join(String(value));
    }
  }
  return text;
}

export function hasTranslation(key: string): boolean {
  return key in DICTS.bn || key in DICTS.en;
}

/** A `t()` bound to this request's language, as the PHP templates have. */
export interface Translator {
  lang: Lang;
  t: (key: string, vars?: Record<string, string | number>) => string;
  digits: (value: string | number) => string;
  number: (value: number, decimals?: number) => string;
  money: (amount: number | null | undefined) => string;
  date: (value: Date | string | null | undefined, format?: DateFormat) => string;
  monthLabel: (yearMonth: string) => string;
  /** Picks `field_bn` in Bangla, `field` otherwise, falling back either way. */
  pick: (row: object, field: string) => string;
  /** For `<field>_bn` / `<field>_en` pairs, as branches and courses store them. */
  pickPair: (row: object, field: string) => string;
  /** An English weekday name from the database, translated. */
  day: (day: unknown) => string;
}

export async function getTranslator(): Promise<Translator> {
  return makeTranslator(await getLang());
}

export function makeTranslator(lang: Lang): Translator {
  return {
    lang,
    t: (key, vars) => translate(lang, key, vars),
    digits: (value) => toLocalDigits(value, lang),
    number: (value, decimals = 0) => formatNumber(value, decimals, lang),
    money: (amount) => formatMoney(amount, lang),
    date: (value, format = 'd M Y') => formatDate(value, format, lang),
    monthLabel: (yearMonth) => monthLabel(yearMonth, lang),
    pick: (row, field) => pickLocalized(row, field, lang),
    pickPair: (row, field) => pickPair(row, field, lang),
    day: (value) => dayName(value, lang),
  };
}

export {
  toLocalDigits,
  formatNumber,
  formatMoney,
  formatDate,
  monthLabel,
  pickLocalized,
  pickPair,
  dayName,
  TEACHING_WEEK,
  todayName,
  type DateFormat,
  type Lang,
} from './format';
