import 'server-only';
import { prisma } from '@/lib/db/prisma';
import { requireRecordBranch } from '@/lib/auth/guards';
import {
  feeAmount,
  feeAmountOrZero,
  feeMethod,
  feeMonth,
  feeDate,
  isFeeType,
  defaultDueDate,
  receiptNumber,
  refreshPlan,
} from '@/lib/fees/core';

/**
 * Recording, settling and removing one student's payments, from
 * admin/payment.php.
 *
 * Three rules from the original that are easy to lose and expensive to lose:
 *
 *   1. **`branch_id` records where the money was taken**, read from the student's
 *      branch at this moment and never rewritten. Branch revenue then stays
 *      right even after the student transfers.
 *   2. **`payment_date` is NOT NULL.** An unpaid row records when it was
 *      entered; marking it paid moves the date to the moment it was paid. The
 *      UI shows the date for paid rows only.
 *   3. **A charge created from an enrollment application is never deleted here.**
 *      It is the record of that transaction and is corrected on the application.
 */

export interface PaymentOutcome {
  ok: boolean;
  /** A translation key. */
  message: string;
}

export interface AddPaymentInput {
  studentId: number;
  amount: string;
  due_amount: string;
  status: string;
  month: string;
  notes: string;
  payment_method: string;
  fee_type: string;
  due_date: string;
}

export async function addPayment(
  input: AddPaymentInput,
  adminId: number
): Promise<PaymentOutcome> {
  const student = await prisma.student
    .findUnique({ where: { id: input.studentId }, select: { id: true, branch_id: true } })
    .catch(() => null);
  if (!student) return { ok: false, message: 'apm.student_not_found' };

  await requireRecordBranch('students', student.id, false);

  const amount = feeAmount(input.amount);
  const due = feeAmountOrZero(input.due_amount);
  const method = feeMethod(input.payment_method);
  const month = input.month.trim();
  const notes = input.notes.slice(0, 2000).trim();
  const status = input.status === 'paid' || input.status === 'unpaid' ? input.status : '';

  if (
    amount === null ||
    due === null ||
    method === null ||
    status === '' ||
    month === '' ||
    month.length > 20
  ) {
    return { ok: false, message: 'astu.msg_invalid' };
  }

  // An unpaid monthly charge with no explicit date falls due on the institute's
  // default due day, which is what makes it show up as overdue later.
  const monthly = feeMonth(month) !== null;
  let dueDate = feeDate(input.due_date);
  if (dueDate === null && status === 'unpaid' && monthly) {
    dueDate = await defaultDueDate(month);
  }

  try {
    await prisma.payment.create({
      data: {
        student_id: student.id,
        amount,
        payment_month: month,
        payment_status: status,
        payment_date: new Date(),
        payment_method: method,
        notes: notes !== '' ? notes : null,
        // `due_amount` is whole taka in the table.
        due_amount: Math.round(due),
        receipt_number: await receiptNumber(),
        branch_id: student.branch_id,
        fee_type: isFeeType(input.fee_type) ? input.fee_type : monthly ? 'monthly' : null,
        due_date: dueDate !== null ? new Date(`${dueDate}T00:00:00.000Z`) : null,
        created_by: adminId > 0 ? adminId : null,
      },
    });
  } catch {
    return { ok: false, message: 'error.generic' };
  }

  return { ok: true, message: 'astu.msg_added' };
}

export async function markPaymentPaid(
  paymentId: number,
  studentId: number
): Promise<PaymentOutcome> {
  const payment = await prisma.payment
    .findFirst({
      where: { id: paymentId, student_id: studentId },
      select: {
        id: true,
        payment_status: true,
        receipt_number: true,
        installment_plan_id: true,
      },
    })
    .catch(() => null);
  if (!payment) return { ok: false, message: 'astu.msg_invalid' };

  await requireRecordBranch('students', studentId, false);

  // Already paid: keep the original payment date rather than moving it to now.
  if (payment.payment_status !== 'paid') {
    try {
      await prisma.payment.update({
        where: { id: payment.id },
        data: {
          payment_status: 'paid',
          payment_date: new Date(),
          // A charge generated by fee management has no receipt number until
          // the money actually arrives.
          ...((payment.receipt_number ?? '') === ''
            ? { receipt_number: await receiptNumber() }
            : {}),
        },
      });
    } catch {
      return { ok: false, message: 'error.generic' };
    }
    await refreshPlan(payment.installment_plan_id);
  }

  return { ok: true, message: 'astu.msg_marked' };
}

export async function deletePayment(
  paymentId: number,
  studentId: number
): Promise<PaymentOutcome> {
  const payment = await prisma.payment
    .findFirst({
      where: { id: paymentId, student_id: studentId },
      select: {
        id: true,
        admission_id: true,
        enrollment_id: true,
        installment_plan_id: true,
      },
    })
    .catch(() => null);
  if (!payment) return { ok: false, message: 'astu.msg_invalid' };

  await requireRecordBranch('students', studentId, false);

  // The enrollment fee verified from an application is the record of that
  // transaction; it is corrected on the application, not deleted here.
  if (payment.admission_id || payment.enrollment_id) {
    return { ok: false, message: 'apm.delete_linked' };
  }

  try {
    await prisma.payment.delete({ where: { id: payment.id } });
  } catch {
    return { ok: false, message: 'error.generic' };
  }
  await refreshPlan(payment.installment_plan_id);

  return { ok: true, message: 'astu.msg_deleted' };
}
